
# n.b. only single line env var is supported
envObj:
  SKIP_CACHEINIT_MAINTENANCE: "somevalue"
  SIIBRA_API_LOG_DIR: /siibra_api_logs/sapi/0.3.33
  SIIBRA_CACHEDIR:  /siibra-api-volume/sapi/0.3.33


image:
  repository: ghcr.io/fzj-inm1-bda/siibra-api
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.3.33"
  spec: "0.3.33"

volumes: 
  - name: log-volume
    persistentVolumeClaim:
      claimName: log-volume-claim
  - name: data-volume
    persistentVolumeClaim:
      claimName: data-volume-claim

volumeMounts: 
  - mountPath: /siibra-api-volume
    name: data-volume
  - mountPath: /siibra_api_logs
    name: log-volume


resources:
  limits:
    cpu: "2"
    memory: 4Gi
  requests:
    cpu: "2"
    memory: 1Gi

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: siibra-api-cdn.apps.dev-adacloud.ebrains.eu
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: sapi-cdn-cert-secret
      hosts:
        - siibra-api-cdn.apps.dev-adacloud.ebrains.eu